server:
  port: 8083

feign:
  sentinel:
    enabled: true

spring:
  application:
    name: user-center

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: true

  datasource:
    # 连接mysql数据库
    url: jdbc:mysql://127.0.0.1:3306/dev_microservice_action?setUnicode=true&characterEncoding=utf8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException，默认：30秒
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 5
      # 连接池中允许的最大连接数。默认：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 15
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10分钟
      idle-timeout: 600000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟，建议设置比数据库超时时长少30秒以上
      max-lifetime: 1800000
      connection-test-query: SELECT 1


  cloud:
    # 限流、流量整形、熔断降级、系统负载保护
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # 设置元数据
    #      metadata:
    #        instance: hello-metadata
    #        version: v1

    # 流量控制、熔断降级、系统负载保护
    sentinel:
      transport:
        # 指定sentinel控制台地址
        dashboard: 127.0.0.1:8080

  # Rabbit MQ 配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: my_vhost
    username: admin
    password: 123456


   