spring:
  application:
    name: content-center
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true

  datasource:
    # 连接mysql数据库
    url: jdbc:mysql://127.0.0.1:3306/dev_microservice_action?setUnicode=true&characterEncoding=utf8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException，默认：30秒
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 5
      # 连接池中允许的最大连接数。默认：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10分钟
      idle-timeout: 600000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟，建议设置比数据库超时时长少30秒以上
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  cloud:
    # 限流、流量整形、熔断降级、系统负载保护
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # 指定命名空间名称
        # namespace: 5c27f9c9-a2e7-4960-b5f4-68fbbafa996a
        # 指定集群名称
        # cluster-name: ChangSha
        # 设置元数据
        metadata:
          instance: hello-metadata
          version: v1

    # 流量控制、熔断降级、系统负载保护
    sentinel:
      filter:
        # 打开/关闭掉对Spring MVC端点的保护
        enabled: true
      transport:
        # 指定sentinel控制台地址
        dashboard: 127.0.0.1:8080
        # 默认8719端口，假如被占用会自动从8719开始一次+1扫描，直至找到未被占用的端口
        port: 8719
    stream:
      binders:
        rabbit_cluster:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: admin
                password: 123456
                virtual-host: my_vhost
      bindings:
        output_channel:
          destination: exchange-content
          group: queue-content
          binder: rabbit_cluster

  # Rabbit MQ 配置
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    virtual-host: my_vhost
#    username: admin
#    password: 123456

# mybatis配置
mybatis:
  # 所有实体类所在包路径
  type-aliases-package: com.moon.content.center.module.domain
  # mapper映射文件
  mapper-locations: classpath:mapper/*.xml

# 配置用户中心的负载均衡规则
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  # 设置ribbon饥饿加载
  eager-load:
    # 开启饥饿加载
    enabled: true
    # 配置需要饥饿加载的服务应用
    clients: user-center
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  ReadTimeout: 60000
  ConnectTimeout: 60000
  OkToRetryOnAllOperations: false

feign:
  sentinel:
    # 为feign整合sentinel
    enabled:  true
  client:
    config:
      # 全局配置日志打印级别
      default:
        loggerLevel: FULL

# RestTemplate 整合 sentinel 配置
resttemplate:
  sentinel:
    # 关闭 @SentinelRestTemplate 注解
    enabled: false

# 所有环境公用的配置属性
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always